# -*- encoding : utf-8 -*-
class BuildServer
  SUCCESS = 0
  ERROR = 1

  PLATFORM_NOT_FOUND = 1
  PLATFORM_PENDING = 2
  PROJECT_NOT_FOUND = 3
  PROJECT_VERSION_NOT_FOUND = 4
  PROJECT_SOURCE_ERROR = 6

  DEPENDENCY_TEST_FAILED = 21
  BINARY_TEST_FAILED = 22

  DEPENDENCIES_ERROR = 555
  BUILD_ERROR = 666
  BUILD_STARTED = 3000
end
