#!/bin/bash

# This file was placed here by rosa-team. It makes sure that your pushed commits will be processed properly.

pwd=`pwd`
reponame=`basename $pwd .git`
owner=`basename \`dirname $pwd\``

while read oldrev newrev ref
do
  newrev_type=$(git cat-file -t $newrev 2> /dev/null)
  oldrev_type=$(git cat-file -t "$oldrev" 2> /dev/null)

  /bin/bash -l -c "cd /srv/rosa_build/current && bundle exec rails runner 'Project.delay.process_hook(\"$owner\", \"$reponame\", \"$newrev\", \"$oldrev\", \"$ref\", \"$newrev_type\", \"$oldrev_type\")'"
done