require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductBuildListsController do

  # This should return the minimal set of attributes required to create a valid
  # ProductBuildList. As you add validations to ProductBuildList, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all product_build_lists as @product_build_lists" do
      product_build_list = ProductBuildList.create! valid_attributes
      get :index
      assigns(:product_build_lists).should eq([product_build_list])
    end
  end

  describe "GET show" do
    it "assigns the requested product_build_list as @product_build_list" do
      product_build_list = ProductBuildList.create! valid_attributes
      get :show, :id => product_build_list.id
      assigns(:product_build_list).should eq(product_build_list)
    end
  end

  describe "GET new" do
    it "assigns a new product_build_list as @product_build_list" do
      get :new
      assigns(:product_build_list).should be_a_new(ProductBuildList)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_build_list as @product_build_list" do
      product_build_list = ProductBuildList.create! valid_attributes
      get :edit, :id => product_build_list.id
      assigns(:product_build_list).should eq(product_build_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductBuildList" do
        expect {
          post :create, :product_build_list => valid_attributes
        }.to change(ProductBuildList, :count).by(1)
      end

      it "assigns a newly created product_build_list as @product_build_list" do
        post :create, :product_build_list => valid_attributes
        assigns(:product_build_list).should be_a(ProductBuildList)
        assigns(:product_build_list).should be_persisted
      end

      it "redirects to the created product_build_list" do
        post :create, :product_build_list => valid_attributes
        response.should redirect_to(ProductBuildList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_build_list as @product_build_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductBuildList.any_instance.stub(:save).and_return(false)
        post :create, :product_build_list => {}
        assigns(:product_build_list).should be_a_new(ProductBuildList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductBuildList.any_instance.stub(:save).and_return(false)
        post :create, :product_build_list => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_build_list" do
        product_build_list = ProductBuildList.create! valid_attributes
        # Assuming there are no other product_build_lists in the database, this
        # specifies that the ProductBuildList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductBuildList.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => product_build_list.id, :product_build_list => {'these' => 'params'}
      end

      it "assigns the requested product_build_list as @product_build_list" do
        product_build_list = ProductBuildList.create! valid_attributes
        put :update, :id => product_build_list.id, :product_build_list => valid_attributes
        assigns(:product_build_list).should eq(product_build_list)
      end

      it "redirects to the product_build_list" do
        product_build_list = ProductBuildList.create! valid_attributes
        put :update, :id => product_build_list.id, :product_build_list => valid_attributes
        response.should redirect_to(product_build_list)
      end
    end

    describe "with invalid params" do
      it "assigns the product_build_list as @product_build_list" do
        product_build_list = ProductBuildList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductBuildList.any_instance.stub(:save).and_return(false)
        put :update, :id => product_build_list.id, :product_build_list => {}
        assigns(:product_build_list).should eq(product_build_list)
      end

      it "re-renders the 'edit' template" do
        product_build_list = ProductBuildList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductBuildList.any_instance.stub(:save).and_return(false)
        put :update, :id => product_build_list.id, :product_build_list => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_build_list" do
      product_build_list = ProductBuildList.create! valid_attributes
      expect {
        delete :destroy, :id => product_build_list.id
      }.to change(ProductBuildList, :count).by(-1)
    end

    it "redirects to the product_build_lists list" do
      product_build_list = ProductBuildList.create! valid_attributes
      delete :destroy, :id => product_build_list.id
      response.should redirect_to(product_build_lists_url)
    end
  end

end
